CREATE TABLE IF NOT EXISTS programas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(40) NULL,
    nombre VARCHAR(180) NOT NULL,
    nivel VARCHAR(80) NULL,
    modalidad VARCHAR(80) NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
