<?php

declare(strict_types=1);

return [
    0 => 'fecha_hora_formulario',
    1 => 'documento_identidad_vigente',
    2 => 'tipo_documento',
    3 => 'programa_formacion',
    4 => 'numero_grupo',
    5 => 'modalidad_formacion',
    6 => 'nombre_completo',
    7 => 'numero_celular',
    8 => 'direccion_domicilio_aprendiz',
    9 => 'ciudad_domicilio_aprendiz',
    10 => 'correo_electronico_personal',
    11 => 'correo_electronico_institucional',
    12 => 'alternativa_ep',
    13 => 'empresa_entidad_coformadora',
    14 => 'direccion_empresa',
    15 => 'direccion_realiza_practica',
    16 => 'nit_empresa',
    17 => 'correo_organizacional',
    18 => 'nombre_jefe',
    19 => 'cargo_jefe',
    20 => 'correo_jefe',
    21 => 'telefono_jefe',
    22 => 'nombre_contacto_2',
    23 => 'correo_contacto_2',
    24 => 'nombre_instructor_seguimiento',
    25 => 'telefono_instructor_seguimiento',
    26 => 'tipo_asistencia',
    27 => 'sugerencias_comentarios',
    28 => 'jefe_grupo',
    29 => 'coordinacion',
    30 => 'ciudad_empresa',
    31 => 'correo_instructor_seguimiento',
];
