<?php

declare(strict_types=1);

/**
 * Plantilla y mapeo de columnas del reporte maestro (RN-28).
 * Columnas alineadas con fila 3 de storage/templates/Reporte Maestro.xlsx.
 *
 * @return array{
 *   template_path: string,
 *   sheet_name: string,
 *   title_row: int,
 *   group_row: int,
 *   header_row: int,
 *   first_data_row: int,
 *   style_source_row: int,
 *   style_range_end: string,
 *   style_highlight_end: string,
 *   advance_highlight_column: string,
 *   protected_columns: list<string>,
 *   formula_columns: list<string>,
 *   columns: array<string, string>,
 *   boolean_keys: list<string>,
 *   date_keys: list<string>,
 * }
 */
return [
    'template_path' => 'storage/templates/Reporte Maestro.xlsx',
    'sheet_name' => 'APRENDICES EP 2024',
    'title_row' => 1,
    'group_row' => 2,
    'header_row' => 3,
    'first_data_row' => 4,
    'style_source_row' => 4,
    'style_range_end' => 'BJ',
    'style_highlight_end' => 'B',
    'advance_highlight_column' => 'I',
    'protected_columns' => ['BL'],
    'formula_columns' => ['N', 'O'],
    'columns' => [
        'num_aprendiz' => 'A',
        'num_por_grupo' => 'B',
        'ficha' => 'C',
        'programa_formacion' => 'D',
        'codigo_programa' => 'E',
        'nivel' => 'F',
        'modalidad_programa' => 'G',
        'fecha_inicio_plataforma' => 'H',
        'inicio_etapa_productiva' => 'I',
        'fecha_fin_plataforma' => 'J',
        'instructor_jefe' => 'K',
        'acuerdo_007' => 'L',
        'acuerdo_009' => 'M',
        'nombre' => 'P',
        'tipo_documento' => 'Q',
        'identificacion' => 'R',
        'celular' => 'S',
        'direccion_domicilio' => 'T',
        'correo' => 'U',
        'modalidad_practica' => 'V',
        'fecha_aval_modalidad' => 'W',
        'estado_arl' => 'X',
        'arl' => 'Y',
        'fecha_inicio_etapa' => 'Z',
        'fecha_fin_etapa' => 'AA',
        'empresa' => 'AB',
        'direccion_empresa' => 'AC',
        'ciudad' => 'AD',
        'contacto_empresa' => 'AE',
        'telefono_contacto' => 'AF',
        'correo_contacto' => 'AG',
        'estado_etapa' => 'AH',
        'llamados_atencion' => 'AI',
        'otros_novedad' => 'AJ',
        'comite_evaluacion' => 'AK',
        'reingreso_vencimiento' => 'AL',
        'observaciones_novedad' => 'AM',
        'doc_gfpi_165' => 'AN',
        'doc_momento_1' => 'AO',
        'doc_bitacora_1' => 'AP',
        'doc_bitacora_2' => 'AQ',
        'doc_bitacora_3' => 'AR',
        'doc_bitacora_4' => 'AS',
        'doc_bitacora_5' => 'AT',
        'doc_bitacora_6' => 'AU',
        'doc_momento_final' => 'AV',
        'cert_doc_identidad' => 'AW',
        'cert_paz_salvo' => 'AX',
        'cert_gfpi_023' => 'AY',
        'cert_bitacoras' => 'AZ',
        'cert_cumplimiento' => 'BA',
        'cert_ape' => 'BB',
        'cert_carnet' => 'BC',
        'cert_saber_tyt' => 'BD',
        'fecha_entrega_admin' => 'BE',
        'estado_aprendiz' => 'BF',
        'observaciones_cert' => 'BG',
        'instructor_asignado' => 'BH',
        'telefono_instructor' => 'BI',
        'correo_instructor' => 'BJ',
    ],
    'boolean_keys' => [
        'acuerdo_007',
        'acuerdo_009',
        'doc_gfpi_165',
        'doc_momento_1',
        'doc_bitacora_1',
        'doc_bitacora_2',
        'doc_bitacora_3',
        'doc_bitacora_4',
        'doc_bitacora_5',
        'doc_bitacora_6',
        'doc_momento_final',
        'cert_doc_identidad',
        'cert_paz_salvo',
        'cert_gfpi_023',
        'cert_bitacoras',
        'cert_cumplimiento',
        'cert_ape',
        'cert_carnet',
        'cert_saber_tyt',
    ],
    'date_keys' => [
        'fecha_inicio_plataforma',
        'inicio_etapa_productiva',
        'fecha_fin_plataforma',
        'fecha_aval_modalidad',
        'fecha_inicio_etapa',
        'fecha_fin_etapa',
        'fecha_entrega_admin',
    ],
];
